was getting below error because wasn't using `self.end_headers()` but not anymore,
```
ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
```

Signed-off-by: TidyData <mckweb@outlook.com>